### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by xaviershay**
See #134 

I wrote this as if all the issues I just filed were fixed. I intend that to be true by the end of the weekend.

### CODE REVIEW

**Comment by xaviershay** [comment]
Actually hold off merging this, I'll just add all the other edits here as well.

**Comment by xaviershay** [comment]
Ready for review.

**Comment by alexdowad** [comment]
Wow, wow, wow. I didn't notice you had added so much here. Let me look through.

**Comment by alexdowad** [comment]
This was a lot of work! Thank you!! Let me go ahead and cherry-pick everything which is ready for merging right now.

**Comment by alexdowad** [comment]
I've merged most of these commits. Will comment on the ones which are not merged yet tomorrow. Thanks!!

**Comment by xaviershay** [comment]
I think I've responded to all feedback.

**Comment by alexdowad** [comment]
Just added some more feedback.

**Comment by alexdowad** [comment]
OK, I've merged the last 3 commits (with a couple tiny edits). Thank you!! Great job!!

**Pull request closed without merging**
