### PR TITLE
factored update_in out of Array and Hash into Associable module

### PR DESCRIPTION
**Pull request by Bill**
Also consolidated specs and updated doc.

YARD-README.md now features `update_in` in a new `Transformations` section.

Renamed `Vector#set` to `Vector#put` to improve consistency with `Hash`. Made `Vector#set` an alias for `Vector#put` until the former can be deprecated.

### CODE REVIEW

**Comment by alexdowad** [comment]
Looks good to me. I'd just like to adjust some spacing in `README.md` before merging.

**Comment by Bill** [comment]
@alexdowad I've never used YARD before. When I ran `rake yard` the output led me to believe that it wasn't meant to be run locally. What is the process for generating and viewing the doc?

**Comment by Bill** [comment]
Woopsie: I had failed to save an update to the new example in the README. Added a commit.

**Comment by alexdowad** [comment]
Merged with some cleanup:

- Made commit message a bit shorter
- New docs in YARD-README.md also added to README.md (the latter is specifically for GitHub)
- Syntax highlighting in README example
- Code formatting in README example

**Comment by alexdowad** [comment]
@Bill Thanks for the great work!

**Comment by Bill** [comment]
You're welcome @alexdowad. That was fun.

**Comment by dubek** [comment]
Thanks @Bill - it looks much better now. Two comments: 

1. in both READMEs - replace the `vector.set` example with `vector.put` (which is now the "correct" method).
2. replace `spec/lib/hamster/vector/set_spec.rb` with `#put` specs, possibly leave a small `#set` spec until we decide to remove that alias. Also other specs that may use `Vector#set`. Possibly comment out the `set` alias and see what breaks.

I'll probably have time tomorrow to fix those two things.

Small suggestion for the future - separate such changes to two commits: first - introduce `Vector#put` (with its relevant documentation and spec changes); second - introduce `Associable` which relies on `Vector#put`.

**Comment by Bill** [comment]
Great @dubek. I agree on all counts and will be more diligent in the future to make PRs that are more focused. Thanks for stepping up to clean this up for me.

**Comment by dubek** [comment]
I pushed those small fixes in e7ad27709bcc22d6c5c29bb68de435a1e43f42b1 .

**Comment by alexdowad** [comment]
Looks nice!

**Pull request closed without merging**
