### PR TITLE
Hamster.to to convert to Ruby collection

### PR DESCRIPTION
**Pull request by elben**
Recursively convert Hamster data to a Ruby collection.

A big use case is marshaling into JSON:

```ruby
require 'json'

data = Hamster::Hash["a" => [1, 2, 3], "b" => Hamster::Hash["c" => "d"]]
Hamster.to(data).to_json
# => "{\"a\":[1,2,3],\"b\":{\"c\":\"d\"}}" 
```

An alternative idea is to make `Hamster::Hash#to_hash` recurse on itself, but this seems like an impractical breaking change.

### CODE REVIEW

**Comment by krainboltgreene** [comment]
I'm not afraid of breaking changes, 2.0.0 isn't a special number to me.

**Comment by alexdowad** [comment]
This seems really useful. Although we have tried to make Hamster collections interface-compatible with built-in Ruby collections, there are times when you want one or the other. I'm just not sure about the name `Hamster.to` -- it is symmetrical with `Hamster.from`, which is nice, but it doesn't seem to describe what it does very well.

`to(arg)` implies that you are converting something to... something described by `arg`. But actually `arg` is what is being converted. That's just English grammar; it might be different in other languages, but to an English-speaking programmer, that is what the syntax brings to mind.

**Comment by elben** [comment]
@krainboltgreene two other problem with `to_hash`:

- It's not a unified interface across all the Hamster collections—we would need `Hamster::Vector#to_a`, `Hamster::Set#to_set` (?).
- It may be expensive, depending on how deep the object is. I'm not sure what user expectations are on a method called `to_hash`.

The `json` module, however, mixes in `Object#to_json`. Maybe Hamster we can do `Hamster::Hash#to_mutable` (and the rest).

@alexdowad on top of the alternative above, what about `Hamster.to_mutable`.

**Comment by krainboltgreene** [comment]
I would rather to_array, but either works.

**Comment by alexdowad** [comment]
We already have `Vector#to_a`, etc. If we are missing other obviously useful conversion methods, we could think about adding them. But this is something a bit different.

Any opinion from @dubek?

**Comment by dubek** [comment]
Although JSON and Yaml modules add `Array#to_json` and `Hash#to_yaml` and so on, I prefer not to go this way (that is, not to add method to basic Ruby objects). 

I'd rather stay with `Hamster::Vector#to_a` as mentioned above. If needed, add `Hamster::Hash#to_h` and `Hamster::Set#to_set` (or maybe `#to_ruby_set` ?)  as needed to convert to regular Ruby objects.

**Comment by krainboltgreene** [comment]
I do enjoy the idea of #to_mutable_x.

**Comment by elben** [comment]
Would you still consider the class method `Hamster.to_mutable` to be a good idea? Three good points I see about this are:

1. Symmetry with `Hamster.from`.
2. Accepts any `Hamster` object.
3. The instance method way (to_set/to_h/to_a) can be implemented by calling `Hamster.to_mutable`.

Otherwise, I can implement the to_x methods individually in each class.

**Comment by elben** [comment]
Also, the Travis CI build fails on ruby-head with what seems to be an interpreter bug. Know anything about this?

https://travis-ci.org/hamstergem/hamster/jobs/54632445#L3490

**Comment by alexdowad** [comment]
"Stack consistency error (sp: 153, bp: 154)" on Ruby 2.3.0dev! This
obviously has nothing to do with @elben's code, so it won't stop it from
being merged in.

**Comment by dubek** [comment]
Yes, you're right. #to_mutable is a good idea.

I wish we had a better name, though. Haven't looked at the equivalent JS
project for ideas yet.

**Comment by elben** [comment]
From [immutable.js](https://github.com/facebook/immutable-js/blob/master/README.md):

All immutable Iterables can be converted to plain JavaScript Arrays and Objects shallowly with `toArray()` and `toObject()` or deeply with `toJS()`. All Immutable Iterables also implement `toJSON()` allowing them to be passed to `JSON.stringify` directly.

```js
var deep = Immutable.Map({ a: 1, b: 2, c: Immutable.List.of(3, 4, 5) });
deep.toObject() // { a: 1, b: 2, c: List [ 3, 4, 5 ] }
deep.toArray() // [ 1, 2, List [ 3, 4, 5 ] ]
deep.toJS() // { a: 1, b: 2, c: [ 3, 4, 5 ] }
JSON.stringify(deep) // '{"a":1,"b":2,"c":[3,4,5]}'
```

----

If we implemented `to_mutable` on each collection, that would result in a similar API (other than supporting `to_json`).

**Comment by alexdowad** [comment]
I think `#to_ruby` reads better than `#to_mutable`. Is it as clear and accurate?

**Comment by dubek** [comment]
I agree with @alexdowad - `#to_ruby` which means "convert to the equivalent built-in Ruby data structure". Then users can have `my_hamster_data_var.to_ruby.to_json` if they wish (or `to_yaml` or whatever).

**Comment by elben** [comment]
Let me know what you think about these latest commits.

```ruby
h=Hamster::Hash[
            "a" => 1,
            "b" => Hamster::Vector[2, Hamster::Hash["c" => 3], 4],
            "d" => Hamster::Set[5, 6, 7],
            "e" => Hamster::Hash["f" => 8, "g" => 9],
            "h" => Regexp.new("ijk"),
            "l" => Hamster::SortedSet.new([1, 2, 3])]
h.to_ruby
# => {"d"=>#<Set: {6, 7, 5}>, "b"=>[2, {"c"=>3}, 4], "h"=>/ijk/, "a"=>1, "e"=>{"f"=>8, "g"=>9}, "l"=>#<SortedSet: {1, 2, 3}>}

Hamster.to_ruby(h)
# => {"d"=>#<Set: {6, 7, 5}>, "b"=>[2, {"c"=>3}, 4], "h"=>/ijk/, "a"=>1, "e"=>{"f"=>8, "g"=>9}, "l"=>#<SortedSet: {1, 2, 3}>}
```

**Comment by krainboltgreene** [comment]
Have I noted before how un-semantic `Hamster::Hash[]` is syntactically?

Anyways, this looks great.

**Comment by elben** [comment]
I don't like the `Class[]` style either—very confusing. This was copy-pasted from a previous test ;).

**Comment by alexdowad** [comment]
A couple comments on the `Class[]` syntax: it was chosen for symmetry with Ruby's built-in `Hash[]`, `Array[]`, and `Set[]`. (If you didn't know about these before, try them in `irb`!)

Previously, a Hamster `Hash` used the same print syntax as a Ruby `Hash`. If you use both in the same program, this meant that when printing things in `irb` or using debug print statements, you couldn't tell which was which. Also, the print syntax could not be `eval`'ed to get an equivalent structure.

The primary disadvantage of the current print syntax is its verbosity. If we could extend Ruby core syntax and add our own data structure literals, that would be better, but it's not possible (not unless immutable data structures were merged into the Ruby interpreter itself).

**Comment by elben** [comment]
Makes sense. I do like being able to paste the print syntax as code.
Homoiconicity!

Let me know if there's anything else I can do for this PR.

**Comment by alexdowad** [comment]
We are making progress here but there is still some work to do. Some things I can see:

- You define a `Convertable` module and then never use it. I would suggest it can just be removed. The method is so short there's not much point in pulling it out into a mixin.
- Making `Hamster.from` support `SortedSet` is good, but you need to `require "hamster/sorted_set"`. Please pull the added support for `SortedSet` in `Hamster.from` out into a single commit of its own, along with the added tests.
- All the work related to `Hamster.to_ruby` should be squashed into a single commit. `git rebase --interactive` is your friend here.
- In your additions to `nested/construction_spec.rb`, the description for the tests for `Hamster.to_ruby` say that it "should return Hamster data". It would be more correct to say it "should return Ruby data structures".

**Comment by alexdowad** [comment]
One more tiny thing is to avoid whitespace changes which are unrelated to what you are doing, since they clutter up diffs. But I can clean that up myself when merging.

**Comment by elben** [comment]
Here's a question, what should this do:

```ruby
Hamster.from({a: :b, c: Hamster.vector(1, 2, {})})
# Currently returns:
# => Hamster::Hash[:a => :b, :c => Hamster::Vector[1, 2, {}]] 
#
# But should it be:
# => Hamster::Hash[:a => :b, :c => Hamster::Vector[1, 2, Hamster::EmptyHash]] 
```

`to_ruby` also has this problem in the inverse.

**Comment by alexdowad** [comment]
I think you are definitely right. It should return the value shown second in the comments.

**Comment by alexdowad** [comment]
Everything looks nice... merging...

**Comment by alexdowad** [comment]
OK, merged! I did some slight cleanup (moved `require "hamster/sorted_set"` to the commit which involves `SortedSet`, etc.), but naturally @elben is still credited as author and commit lines and dates are the same as I fetched from his repo.

**Comment by elben** [comment]
Thanks!

What is your workflow for such surgical commit blob modifications? My slow method to fix the dangling `require "hamster/sorted_set"` would have been to:

- Create new commit that removes the require. Rebase with existing commit that didn't need the require.
- Create new commit that re-adds the require. Rebase with sorted_set commit.

**Comment by alexdowad** [comment]
@elben, there are lots of ways to work on git commit history, and my ways are probably not the best at all. In many cases I would do exactly what you just described. What I just did was a bit different:

1. Fetch from your repo.
2. From `master`, run `git format-patch master..remotes/elben/to-nested-ruby-collection`. Now there are a bunch of `.patch` files in the working directory.
3. Apply the first patch with `git am`.
4. Touch things up and `git commit --amend`.
5. Look at it with `git show` to make sure everything looks good.
6. Apply the next patch with `git am`...
7. Repeat until done.

**Pull request closed without merging**
