### PR TITLE
Modernize rspec syntax

### PR DESCRIPTION
**Pull request by ivoanjo**
Hello there! Thanks for your awesome work on hamster! :tada:

I work on a gem called [`persistent-💎`](https://github.com/ivoanjo/persistent-dmnd) that builds on top of Hamster but offers a nice beautiful (opinionated?) shorthand syntax to create the persistent data structures.

As part of my work I'd like to contribute some improvements I did on top of Hamster back upstream.

As a start, this CR updates the test suite to use the latest rspec syntax. These changes were automatically performed using the [`transpec`](https://github.com/yujinakayama/transpec) gem.

### CODE REVIEW

**Comment by alexdowad** [comment]
Looks good (I looked through the whole thing, although it's quite long).

**Comment by alexdowad** [comment]
Hmm. Just tried 'Update branch' button. Not sure if that was a good idea, or if it will introduce ugly merge commits into the history. If need be, I may just download your commits as patch files and apply them to HEAD.

**Comment by ivoanjo** [comment]
Rebase pushed.

**Comment by alexdowad** [comment]
Thanks very much!

**Pull request merged**
