### PR TITLE
Fix minor error in benchmark messages

### PR DESCRIPTION
**Pull request by no-reply**
Corrects mistaken benchmark descriptions in `bench/hash/get_bench.rb`.

### CODE REVIEW

**Comment by alexdowad** [comment]
Travis CI failure has nothing to do with @no-reply's change. It's one of the random failures which has become all too common on their platform.

**Comment by no-reply** [comment]
These errors seem connected to the version of RubyGems/bundler pairing used. See https://github.com/bundler/bundler/issues/3558

I pushed a change to force an upgrade to both. 

If the upgraded `.travis.yml` should be a separate PR, let me know. I'm happy to split it out.

**Comment by no-reply** [comment]
The `jruby-head` build is still broken after dff86bb. I'm not going to worry about it, since it's an allowed failure and probably a jruby and/or bundler problem.

**Comment by alexdowad** [comment]
Looks good! Thanks!

**Pull request merged**
