### PR TITLE
Fix set specs.

### LINKED ISSUE #213: test: set/grep_spec.rb skips all examples
```
$ bundle exec rspec spec/lib/hamster/set/grep_spec.rb 
I, [2015-12-04T17:42:14.953523 #14572]  INFO -- : Not reporting to Code Climate because ENV['CODECLIMATE_REPO_TOKEN'] is not set.
Performance on MRI may be improved with the concurrent-ruby-ext gem. Please see http://concurrent-ruby.com
No examples found.

Finished in 0.00019 seconds (files took 0.94008 seconds to load)
0 examples, 0 failures

Top 0 slowest examples (0 seconds, 0.0% of total time):
```

Running in MRI 2.2.3 on Linux.

I must say I don't completely understand all this rspec magic, so if someone here knows the answer that might be faster/cleaner way to fix. Other than that, I can try to remove all the `shared_examples` and make everything inline.

### PR DESCRIPTION
**Pull request by xaviershay**
cc @alexdowad not sure how things got into this state, also not sure what the `downcase` was supposed to be testing.

Fixes #213.

### CODE REVIEW

**Comment by dubek** [comment]
The downcase should verify that the filtered results indeed are processed by the block (when given) - similar to #map behavior.

**Comment by xaviershay** [comment]
that might need to get pulled out of shared specs then, since `"A" != "a"`

**Comment by dubek** [comment]
Yes, you're right. IMO there's no need to repeat all the scenarios again *with* the block, maybe just verify that:

    Hamster::Set["A", 2, "C"].grep(String) { |x| x.downcase }
    #=> Hamster::Set["a", "c"]

**Comment by alexdowad** [comment]
Nice catch! Looks like this problem dates back to 2013.

**Comment by alexdowad** [comment]
@xaviershay , do you want to amend the test so it actually checks that `#grep` maps results through the block? Or would you like this patch to be merged first?

**Comment by dubek** [comment]
@alexdowad why was this closed? AFAIK the issue is still there:

```
$ rspec spec/lib/hamster/set/grep_spec.rb 
I, [2015-12-07T09:04:47.020231 #23152]  INFO -- : Not reporting to Code Climate because ENV['CODECLIMATE_REPO_TOKEN'] is not set.
No examples found.

Finished in 0.00018 seconds (files took 1.5 seconds to load)
0 examples, 0 failures

Top 0 slowest examples (0 seconds, 0.0% of total time):
```

**Comment by alexdowad** [comment]
I must have accidentally clicked "Comment and close" rather than "Comment". That wasn't my intention. Sorry.

**Comment by dubek** [comment]
@xaviershay Can you please rebase your branch on top of the current `master`, and add a verification that `#grep` processes results with the given block (as discussed above)?

**Comment by xaviershay** [comment]
sure, not going to get to this for a few days though.

**Pull request closed without merging**
