### PR TITLE
Edit Hash documentation.

### PR DESCRIPTION
**Pull request by xaviershay**
* Tightened up introduction, removing some words and pushing details down into method docs.
* Demoted `#store` from introduction. All `#put`, all the time.
* Promoted `#update_in` to introduction, since it is non-obvious and particularly handy with immutable structures.
* Added missing yield documentation
* Clarified some edge case behaviour. Mostly obvious, but doesn't hurt to include.
* Assorted typos and grammar fixes.

Addresses part of https://github.com/hamstergem/hamster/issues/134. If this is the kind of thing you were hoping for, I can go ahead and tackle the other classes.

cc @alexdowad

### CODE REVIEW

**Comment by alexdowad** [comment]
Wow, this is just the kind of thing I was hoping for when I opened this issue. Nice! Note that "syntax" is not a countable noun -- "a syntax" sounds strange.

**Comment by alexdowad** [comment]
"data structure" is 2 words, not 1.

**Comment by alexdowad** [comment]
"Otherwise", not "Otherwie".

**Comment by alexdowad** [comment]
"calling the block with the key", not "called the block with the key".

**Comment by xaviershay** [comment]
thanks for feedback, will address tomorrow.

**Comment by xaviershay** [comment]
Updated. I think your last two comments were on the old version rather than the new (called, Otherwie).

**Comment by alexdowad** [comment]
OK, I think this is good to merge. The one thing is that the documentation for `#to_ruby` is not quite accurate -- it says "no Hamster structures will remain", but `#to_ruby` doesn't convert `Hamster::Deque` into core Ruby structures. (Sounds like something we should fix...)

**Comment by alexdowad** [comment]
Merged. @xaviershay, thanks for your contribution. Please work on the docs for the other classes if you can.

**Comment by xaviershay** [comment]
great thanks, I'll start tackling the others!

**Comment by alexdowad** [comment]
I just fixed `Hamster.to_ruby` so it also converts `Hamster::Deque` structures.

**Pull request closed without merging**
