### PR TITLE
Remove circular dependency between nested and core classes.

### PR DESCRIPTION
**Pull request by xaviershay**
One possible way to do this. Not convinced it's the best but not sure what would be better.

Ref #196

### CODE REVIEW

**Comment by alexdowad** [comment]
Again, very interesting. I hadn't thought of doing it this way. Comments from other contributors?

**Comment by dubek** [comment]
Thanks for noticing this.

Another option is to completely remove the per-class `#to_ruby` methods. To look at another example, I really prefer `JSON.generate(obj)` instead of `obj.to_json`; that also allows having `JSON.pretty_generate(obj)`, `MessagePack.pack(obj)` and so on without further polluting the classes interface.

To contradict myself, the current `Hamster.to_ruby` has a code smell in which we switch over the argument's class, which is something that should classically be done with polymorphism. So another approach is that each class will implement its own `#to_ruby`, calling `.to_ruby` on each collection element (hmm, but what about plain Ruby classes?).

**Comment by xaviershay** [comment]
@dubek for your first option, we could just remove all the `#to_ruby` methods. I'm actually on board with that, but needs a major version release.

For the latter, easy enough to do a `respond_to?(:to_ruby)` check?

**Comment by dubek** [comment]
But if an object doesn't `respond_to?(:to_ruby)`, you'll need to implement the `when Hash ... when Array ...` etc. You *don't* want that code duplicated in `Hamster::Hash#to_ruby` and `Hamster::Vector#to_ruby` and so on.

Maybe the code smell I was referring to is unavoidable, because we want to support both the Hamster classes and the PORO collections.

**Comment by alexdowad** [comment]
As an opinion, I don't think switching on object class is *always* a "code smell". It's a question of how you want to organize your code: would you rather have all the code for `Vector` (as an example) together, or would you rather have all the code for conversion to Ruby structures together? The second consideration is whether new classes which should be convertible to Ruby structures are likely to be added frequently.

I would be happy to just use `Hamster.to_ruby(obj)` rather than `obj.to_ruby`. It seems that @dubek likes this option. @xaviershay hasn't expressed an opinion. Preferences, anyone else?

**Comment by xaviershay** [comment]
`Hamster.to_ruby(obj)` works for me, but needs a major version bump coz it's backwards incompatible to remove the `to_ruby` methods. (Not sure what your release policy/cadence is...)

**Comment by alexdowad** [comment]
@xaviershay, that's not a problem, since `#to_ruby` was not even included in the last gem release. (Have a look at the git history.)

**Comment by alexdowad** [comment]
It seems no further comments are forthcoming? So can we go ahead and remove the per-class `#to_ruby` methods, and let people use `Hamster.from` and `Hamster.to` instead?

**Comment by dubek** [comment]
I'm OK with it. The docs for `Hamster.to_ruby` should be updated, not sure if anyone tackled it already.

**Comment by alexdowad** [comment]
@xaviershay, would you like to code up a patch for this? If you don't want to, I will go ahead and do it.

**Comment by xaviershay** [comment]
I don't have any free time until the weekend, if it's not done by then I'll have a look :)

**Comment by alexdowad** [comment]
Just removed `#to_ruby` in 30a6aa8. Our problems with circular dependencies are greatly reduced. Have a look:

depgraph

**Comment by alexdowad** [comment]
@dubek I just updated the docstrings for `.to_ruby` and `.from`.

**Pull request closed without merging**
