### PR TITLE
Fix Hamster on Ruby 3.0

### PR DESCRIPTION
**Pull request by alexdowad**
Thanks to @dleidert for reporting that Hamster has problems on Ruby 3.0. This PR should fix it.

@dubek Are you available to review?

### CODE REVIEW

**Comment by dubek** [comment]
I'll get to it in the next day or two.

**Review by dubek — APPROVED** [review]
Looks good.

Another PR should probably update the whole CI:
- move to github workflows/actions
- use Ruby 2.x and 3.x, remove unsupported versions

(I must say I haven't been regularly using Ruby for the last ~5 years. Never used Ruby 3.)

**Comment by alexdowad** [comment]
Thanks so much for the review.

> Another PR should probably update the whole CI:

If the library was under active development, then definitely, yes. But since it's feature-complete and we are only getting bug reports at a rate of one every couple of years...

> (I must say I haven't been regularly using Ruby for the last ~5 years. Never used Ruby 3.)

Out of curiosity, are you still doing software? What is your current set of preferred tools?

**Comment by dubek** [comment]
> Out of curiosity, are you still doing software? What is your current set of preferred tools?

In the last year I'm working on confidential computing, so mainly C (linux kernel, qemu, edk2) and bits of Rust (kata-containers and other projects).

**Comment by alexdowad** [comment]
> In the last year I'm working on confidential computing, so mainly C (linux kernel, qemu, edk2) and bits of Rust (kata-containers and other projects).

Cool stuff. 👍🏻

**Pull request merged**
