### PR TITLE
Fix 2.2.2+ segfault in Hamster.from for certain inputs.

### LINKED ISSUE #189: Segfault in 2.2.2 and above
The following segfaults on master (not released 1.0.0 gem) 2.2.2 and above. Can be seen in travis CI.

``` ruby
input = {
  "i" => Hamster::Hash["k" => Hamster::Set[1]]
}

Hamster.from(input)
```

```
/Users/xavier/Code/ex/hamster/lib/hamster/trie.rb:32: [BUG] Stack consistency error (sp: 47, bp: 48)
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.

-- Control frame information -----------------------------------------------
c:0014 p:0018 s:0047 e:000047 BLOCK  /Users/xavier/Code/ex/hamster/lib/hamster/trie.rb:32 [FINISH]
c:0013 p:---- s:0045 e:000044 CFUNC  :each
c:0012 p:0009 s:0042 e:000041 METHOD /Users/xavier/Code/ex/hamster/lib/hamster/trie.rb:32
c:0011 p:0028 s:0038 e:000037 METHOD /Users/xavier/Code/ex/hamster/lib/hamster/hash.rb:348 [FINISH]
c:0010 p:---- s:0034 E:000578 CFUNC  :map
c:0009 p:0041 s:0031 e:000029 METHOD /Users/xavier/Code/ex/hamster/lib/hamster/hash.rb:424
c:0008 p:0162 s:0027 E:000a00 METHOD /Users/xavier/Code/ex/hamster/lib/hamster/nested.rb:27
c:0007 p:0014 s:0022 e:000020 BLOCK  /Users/xavier/Code/ex/hamster/lib/hamster/nested.rb:24 [FINISH]
c:0006 p:---- s:0017 e:000016 IFUNC
c:0005 p:---- s:0015 e:000014 CFUNC  :each
c:0004 p:---- s:0013 e:000012 CFUNC  :map
c:0003 p:0136 s:0010 e:000009 METHOD /Users/xavier/Code/ex/hamster/lib/hamster/nested.rb:24
c:0002 p:0056 s:0005 E:000208 EVAL   /tmp/test.rb:19 [FINISH]
c:0001 p:0000 s:0002 E:001c40 TOP    [FINISH]

-- Ruby level backtrace information ----------------------------------------
/tmp/test.rb:19:in `<main>'
/Users/xavier/Code/ex/hamster/lib/hamster/nested.rb:24:in `from'
/Users/xavier/Code/ex/hamster/lib/hamster/nested.rb:24:in `map'
/Users/xavier/Code/ex/hamster/lib/hamster/nested.rb:24:in `each'
/Users/xavier/Code/ex/hamster/lib/hamster/nested.rb:24:in `block in from'
/Users/xavier/Code/ex/hamster/lib/hamster/nested.rb:27:in `from'
/Users/xavier/Code/ex/hamster/lib/hamster/hash.rb:424:in `map'
/Users/xavier/Code/ex/hamster/lib/hamster/hash.rb:424:in `map'
/Users/xavier/Code/ex/hamster/lib/hamster/hash.rb:348:in `each'
/Users/xavier/Code/ex/hamster/lib/hamster/trie.rb:32:in `each'
/Users/xavier/Code/ex/hamster/lib/hamster/trie.rb:32:in `each'
/Users/xavier/Code/ex/hamster/lib/hamster/trie.rb:32:in `block in each'

-- C level backtrace information -------------------------------------------
0   ruby                                0x000000010a3bd735 rb_vm_bugreport + 149
1   ruby                                0x000000010a260754 rb_bug + 468
2   ruby                                0x000000010a39f693 vm_exec_core + 17347
3   ruby                                0x000000010a3ae931 vm_exec + 129
4   ruby                                0x000000010a3b3b08 invoke_block_from_c + 2408
5   ruby                                0x000000010a3aad80 rb_yield + 192
6   ruby                                0x000000010a221e79 rb_ary_each + 89
7   ruby                                0x000000010a3bb6c4 vm_call_cfunc + 1764
8   ruby                                0x000000010a3ba7b2 vm_call_method + 882
9   ruby                                0x000000010a39e720 vm_exec_core + 13392
10  ruby                                0x000000010a3ae931 vm_exec + 129
11  ruby                                0x000000010a3ab4ec iterate_method + 220
12  ruby                                0x000000010a3ab329 rb_iterate + 441
13  ruby                                0x000000010a3ab3fd rb_block_call + 45
14  ruby                                0x000000010a257076 enum_collect + 54
15  ruby                                0x000000010a3bb6c4 vm_call_cfunc + 1764
16  ruby                                0x000000010a3ba7b2 vm_call_method + 882
17  ruby                                0x000000010a39ed15 vm_exec_core + 14917
18  ruby                                0x000000010a3ae931 vm_exec + 129
19  ruby                                0x000000010a3b3b08 invoke_block_from_c + 2408
20  ruby                                0x000000010a3aafe7 rb_yield_values2 + 103
21  ruby                                0x000000010a25b863 collect_i + 19
22  ruby                                0x000000010a3b3830 invoke_block_from_c + 1680
23  ruby                                0x000000010a3aad80 rb_yield + 192
24  ruby                                0x000000010a295a41 each_pair_i + 17
25  ruby                                0x000000010a296305 hash_foreach_iter + 37
26  ruby                                0x000000010a342321 st_foreach_check + 113
27  ruby                                0x000000010a28f2a2 hash_foreach_call + 34
28  ruby                                0x000000010a26a70e rb_ensure + 174
29  ruby                                0x000000010a292caa rb_hash_each_pair + 154
30  ruby                                0x000000010a3b7bc8 vm_call0_body + 2328
31  ruby                                0x000000010a3ab4ec iterate_method + 220
32  ruby                                0x000000010a3ab329 rb_iterate + 441
33  ruby                                0x000000010a3ab3fd rb_block_call + 45
34  ruby                                0x000000010a257076 enum_collect + 54
35  ruby                                0x000000010a3bb6c4 vm_call_cfunc + 1764
36  ruby                                0x000000010a3ba7b2 vm_call_method + 882
37  ruby                                0x000000010a39e720 vm_exec_core + 13392
38  ruby                                0x000000010a3ae931 vm_exec + 129
39  ruby                                0x000000010a3afa38 rb_iseq_eval_main + 504
40  ruby                                0x000000010a269764 ruby_exec_internal + 148
41  ruby                                0x000000010a26968e ruby_run_node + 78
42  ruby                                0x000000010a21f33f main + 79

-- Other runtime information -----------------------------------------------

* Loaded script: /tmp/test.rb

* Loaded features:

    0 enumerator.so
    1 rational.so
    2 complex.so
    3 /Users/xavier/.rubies/cruby-2.2.2/lib/ruby/2.2.0/x86_64-darwin14/enc/encdb.bundle
    4 /Users/xavier/.rubies/cruby-2.2.2/lib/ruby/2.2.0/x86_64-darwin14/enc/trans/transdb.bundle
    5 /Users/xavier/.rubies/cruby-2.2.2/lib/ruby/2.2.0/unicode_normalize.rb
    6 /Users/xavier/.rubies/cruby-2.2.2/lib/ruby/2.2.0/x86_64-darwin14/rbconfig.rb
    7 thread.rb
    8 /Users/xavier/.rubies/cruby-2.2.2/lib/ruby/2.2.0/x86_64-darwin14/thread.bundle
    9 /Users/xavier/.rubies/cruby-2.2.2/lib/ruby/2.2.0/rubygems/compatibility.rb
   10 /Users/xavier/.rubies/cruby-2.2.2/lib/ruby/2.2.0/rubygems/defaults.rb
   11 /Users/xavier/.rubies/cruby-2.2.2/lib/ruby/2.2.0/rubygems/deprecate.rb
   12 /Users/xavier/.rubies/cruby-2.2.2/lib/ruby/2.2.0/rubygems/errors.rb
   13 /Users/xavier/.rubies/cruby-2.2.2/lib/ruby/2.2.0/rubygems/version.rb
   14 /Users/xavier/.rubies/cruby-2.2.2/lib/ruby/2.2.0/rubygems/requirement.rb
   15 /Users/xavier/.rubies/cruby-2.2.2/lib/ruby/2.2.0/rubygems/platform.rb
   16 /Users/xavier/.rubies/cruby-2.2.2/lib/ruby/2.2.0/rubygems/basic_specification.rb
   17 /Users/xavier/.rubies/cruby-2.2.2/lib/ruby/2.2.0/rubygems/stub_specification.rb
   18 /Users/xavier/.rubies/cruby-2.2.2/lib/ruby/2.2.0/rubygems/util/stringio.rb
   19 /Users/xavier/.rubies/cruby-2.2.2/lib/ruby/2.2.0/rubygems/specification.rb
   20 /Users/xavier/.rubies/cruby-2.2.2/lib/ruby/2.2.0/rubygems/exceptions.rb
   21 /Users/xavier/.rubies/cruby-2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb
   22 /Users/xavier/.rubies/cruby-2.2.2/lib/ruby/2.2.0/monitor.rb
   23 /Users/xavier/.rubies/cruby-2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb
   24 /Users/xavier/.rubies/cruby-2.2.2/lib/ruby/2.2.0/rubygems.rb
   25 /Users/xavier/.rubies/cruby-2.2.2/lib/ruby/2.2.0/set.rb
   26 /Users/xavier/Code/ex/hamster/lib/hamster/immutable.rb
   27 /Users/xavier/Code/ex/hamster/lib/hamster/undefined.rb
   28 /Users/xavier/Code/ex/hamster/lib/hamster/enumerable.rb
   29 /Users/xavier/Code/ex/hamster/lib/hamster/trie.rb
   30 /Users/xavier/Code/ex/hamster/lib/hamster/sorted_set.rb
   31 /Users/xavier/Code/ex/hamster/lib/hamster/set.rb
   32 /Users/xavier/Code/ex/hamster/lib/hamster/vector.rb
   33 /Users/xavier/Code/ex/hamster/lib/hamster/hash.rb
   34 /Users/xavier/Code/ex/hamster/lib/hamster/nested.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
Don't forget to include the above Crash Report log file.
For details: http://www.ruby-lang.org/bugreport.html
```

I am investigating.

### PR DESCRIPTION
**Pull request by xaviershay**
The fault appears to be an issue with mixing &block and yield, but I couldn't
figure out a more minimal repro.

Fixes #189

### CODE REVIEW

**Comment by alexdowad** [comment]
Thanks for the fix -- but I would like to dig into the interpreter code and find out exactly why it is segfaulting before we merge any fix.

**Comment by xaviershay** [comment]
I want to keep digging into details too, but having a red CI is really concerning to me. Would you accept marking this spec as pending instead?

**Comment by xaviershay** [comment]
Should revert https://github.com/hamstergem/hamster/pull/195 once this (or an alternate fix) is applied.

**Comment by xaviershay** [comment]
@alexdowad WDYT of this comment?

**Comment by alexdowad** [comment]
Looks great, let me merge.

**Comment by alexdowad** [comment]
Merged.

**Pull request closed without merging**
